Repository leon-cleaning-services/leon, pull requests merged in 2022-11, with the labels that each got.

#88 chore: Automatically increment version code
  .github/workflows/build.yml
  .github/workflows/deploy.yml
  app/build.gradle.kts
Labels: chore

#92 fix: Fix build issue on F-Droid
  CHANGELOG.md
  app/build.gradle.kts
Labels: bug

#93 feat: Automatically create GitHub releases
  .github/workflows/build.yml
  .github/workflows/deploy.yml
Labels: feature

#96 fix: Remove git-secret from build.yml workflow
  .github/workflows/build.yml
  app/build.gradle.kts
Labels: fix

#94 Add Aliexpress sanitizer
  app/src/main/kotlin/com/svenjacobs/app/leon/sanitizer/aliexpress/AliexpressSanitizer.kt
  app/src/main/kotlin/com/svenjacobs/app/leon/startup/ContainerInitializer.kt
  app/src/main/res/values/strings.xml
  app/src/test/kotlin/com/svenjacobs/app/leon/sanitizer/aliexpress/AliexpressSanitizerTest.kt
Labels: feature

#99 feat: Update dependencies
  gradle/libs.versions.toml
Labels: feature

#100 feat: Prepare README.md for all-contributors
  README.md
Labels: feature

#124 Support LinkSynergy links, fix #84
  app/src/main/kotlin/com/svenjacobs/app/leon/sanitizer/linksynergy/LinkSynergySanitizer.kt
  app/src/main/kotlin/com/svenjacobs/app/leon/startup/ContainerInitializer.kt
  app/src/main/res/values/strings.xml
  app/src/test/kotlin/com/svenjacobs/app/leon/sanitizer/linksynergy/LinkSynergySanitizerTest.kt
Labels: feature

#126 feat: Add support for GeoRiot links, fix #82
  app/src/main/kotlin/com/svenjacobs/app/leon/sanitizer/georiot/GeoRiotSanitizer.kt
  app/src/main/kotlin/com/svenjacobs/app/leon/startup/ContainerInitializer.kt
  app/src/main/res/values/strings.xml
  app/src/test/kotlin/com/svenjacobs/app/leon/sanitizer/georiot/GeoRiotSanitizerTest.kt
Labels: feature

#129 doc: Update documentation
  CHANGELOG.md
  CONTRIBUTING.md
Labels: documentation

#130 fix: Fix deploy workflow
  .github/workflows/deploy.yml
  app/build.gradle.kts
Labels: bug

#131 chore: Increment version name in deploy workflow
  .github/workflows/deploy.yml
Labels: chore

#132 chore: Add generic release texts for F-Droid & Play Store
  app/src/main/play/release-notes/de-DE/default.txt
  app/src/main/play/release-notes/en-US/default.txt
Labels: chore

#134 chore: Update dependencies
  gradle/libs.versions.toml
Labels: chore

#137 feat: Add YouTube Music sanitizer
  app/src/main/kotlin/com/svenjacobs/app/leon/startup/ContainerInitializer.kt
  core-domain/src/main/kotlin/com/svenjacobs/app/leon/core/domain/sanitizer/youtube/YoutubeMusicSanitizer.kt
  core-domain/src/main/res/values/strings.xml
  core-domain/src/test/kotlin/com/svenjacobs/app/leon/core/domain/sanitizer/youtube/YoutubeMusicSanitizerTest.kt
Labels: feature

#138 chore: Improve deploy workflow
  .github/workflows/deploy.yml
Labels: chore
