Repository leon-cleaning-services/leon, pull requests merged in 2023-05, with the labels that each got.

#165 chore: Update lots of dependencies
  .github/workflows/build.yml
  .github/workflows/deploy.yml
  app/build.gradle.kts
  buildSrc/src/main/kotlin/Android.kt
  gradle.properties
  gradle/libs.versions.toml
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
Labels: chore

#167 Elfinanciero sanitizer
  app/src/main/kotlin/com/svenjacobs/app/leon/startup/ContainerInitializer.kt
  core-domain/src/main/kotlin/com/svenjacobs/app/leon/core/domain/sanitizer/elfinanciero/ElFinancieroSanitizer.kt
  core-domain/src/main/res/values/strings.xml
  core-domain/src/test/kotlin/com/svenjacobs/app/leon/core/domain/sanitizer/elfinanciero/ElFinancieroSanitizerTest.kt
Labels: feature

#171 chore: Update dependencies
  gradle/libs.versions.toml
Labels: chore

#173 fix: Add missing domain check to elfinanciero.com.mx sanitizer
  core-domain/src/main/kotlin/com/svenjacobs/app/leon/core/domain/sanitizer/elfinanciero/ElFinancieroSanitizer.kt
  core-domain/src/test/kotlin/com/svenjacobs/app/leon/core/domain/sanitizer/elfinanciero/ElFinancieroSanitizerTest.kt
Labels: bug

#174 feat: Add Lazada sanitizer
  app/src/main/kotlin/com/svenjacobs/app/leon/startup/ContainerInitializer.kt
  core-domain/src/main/kotlin/com/svenjacobs/app/leon/core/domain/sanitizer/lazada/LazadaSanitizer.kt
  core-domain/src/main/res/values/strings.xml
  core-domain/src/test/kotlin/com/svenjacobs/app/leon/core/domain/sanitizer/lazada/LazadaSanitizerTest.kt
Labels: feature

#175 feat: Add Shopee sanitizer
  app/src/main/kotlin/com/svenjacobs/app/leon/startup/ContainerInitializer.kt
  core-domain/src/main/kotlin/com/svenjacobs/app/leon/core/domain/sanitizer/shopee/ShopeeSanitizer.kt
  core-domain/src/main/res/values/strings.xml
  core-domain/src/test/kotlin/com/svenjacobs/app/leon/core/domain/sanitizer/shopee/ShopeeSanitizerTest.kt
Labels: feature

#176 feat: Replace "Verify" by "Open" functionality
  app/build.gradle.kts
  app/src/main/kotlin/com/svenjacobs/app/leon/MainActivity.kt
  app/src/main/kotlin/com/svenjacobs/app/leon/ui/screens/main/MainScreen.kt
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-pl/strings.xml
  app/src/main/res/values-ru/strings.xml
  app/src/main/res/values/strings.xml
  gradle/libs.versions.toml
Labels: feature

#179 feat: Add sanitizer for The Guardian
  app/src/main/kotlin/com/svenjacobs/app/leon/startup/ContainerInitializer.kt
  core-domain/src/main/kotlin/com/svenjacobs/app/leon/core/domain/sanitizer/theguardian/TheGuardianSanitizer.kt
  core-domain/src/main/res/values/strings.xml
  core-domain/src/test/kotlin/com/svenjacobs/app/leon/core/domain/sanitizer/theguardian/TheGuardianSanitizerTest.kt
Labels: feature

#180 feat: Improve Amazon product sanitizer
  core-domain/src/main/kotlin/com/svenjacobs/app/leon/core/domain/sanitizer/amazon/AmazonProductSanitizer.kt
  core-domain/src/test/kotlin/com/svenjacobs/app/leon/core/domain/sanitizer/amazon/AmazonProductSanitizerTest.kt
Labels: feature

#181 chore: Update dependencies
  gradle/libs.versions.toml
Labels: chore

#183 fix: Use M3 version of ExposedDropdownMenu
  app/src/main/kotlin/com/svenjacobs/app/leon/ui/screens/settings/SettingsScreen.kt
  app/src/main/kotlin/com/svenjacobs/app/leon/ui/tooling/DayNightPreviews.kt
Labels: bug

#184 fix: Amazon product sanitizer for cart links
  core-domain/src/main/kotlin/com/svenjacobs/app/leon/core/domain/sanitizer/amazon/AmazonProductSanitizer.kt
  core-domain/src/test/kotlin/com/svenjacobs/app/leon/core/domain/sanitizer/amazon/AmazonProductSanitizerTest.kt
Labels: bug, fix
