Repository leon-cleaning-services/leon, pull requests merged in 2024-01, with the labels that each got.

#340 Fix Instagram (igshid -> igsh)
  core-domain/src/main/kotlin/com/svenjacobs/app/leon/core/domain/sanitizer/instagram/InstagramSanitizer.kt
  core-domain/src/test/kotlin/com/svenjacobs/app/leon/core/domain/sanitizer/instagram/InstagramSanitizerTest.kt
Labels: bug

#343 chore: Update dependencies
  .idea/inspectionProfiles/Project_Default.xml
  app/build.gradle.kts
  app/src/main/kotlin/com/svenjacobs/app/leon/ui/screens/settings/SettingsLicensesScreen.kt
  gradle/libs.versions.toml
  gradle/wrapper/gradle-wrapper.properties
  gradlew
Labels: dependencies

#344 fix: YT sanitizer for playlist URLs
  core-domain/src/main/kotlin/com/svenjacobs/app/leon/core/domain/sanitizer/youtube/YoutubeSanitizer.kt
  core-domain/src/test/kotlin/com/svenjacobs/app/leon/core/domain/sanitizer/youtube/YoutubeSanitizerTest.kt
Labels: bug

#345 fix: Vietnamese translation folder name
  app/src/main/res/values-vi/a11y.xml
  app/src/main/res/values-vi/strings.xml
Labels: bug

#348 feat: Add support for per-app language preferences
  app/build.gradle.kts
  app/src/main/res/resources.properties
Labels: feature

#352 feat: Make original & cleaned URL selectable
  app/src/main/kotlin/com/svenjacobs/app/leon/ui/screens/main/MainScreen.kt
Labels: feature
