Repository leon-cleaning-services/leon, pull requests merged in 2024-10, with the labels that each got.

#480 chore: update Gradle to 8.10.2
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
Labels: dependencies

#485 chore: update AboutLibraries
  app/build.gradle.kts
  build.gradle.kts
  gradle/libs.versions.toml
Labels: dependencies

#486 feat: add explanation for context menu functionality
  README.md
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values/strings.xml
  etc/context_menu.png
Labels: documentation

#491 Add MyDealz sanitizer as per #358
  app/src/main/kotlin/com/svenjacobs/app/leon/startup/ContainerInitializer.kt
  core-domain/src/main/kotlin/com/svenjacobs/app/leon/core/domain/sanitizer/mydealz/MyDealzDomains.kt
  core-domain/src/main/kotlin/com/svenjacobs/app/leon/core/domain/sanitizer/mydealz/MyDealzParametersSanitizer.kt
  core-domain/src/main/kotlin/com/svenjacobs/app/leon/core/domain/sanitizer/mydealz/MyDealzRedirectsSanitizer.kt
  core-domain/src/main/res/values-de/strings.xml
  core-domain/src/main/res/values-ru/strings.xml
  core-domain/src/main/res/values/strings.xml
  core-domain/src/test/kotlin/com/svenjacobs/app/leon/core/domain/sanitizer/mydealz/MyDealzParametersSanizierTest.kt
  core-domain/src/test/kotlin/com/svenjacobs/app/leon/core/domain/sanitizer/mydealz/MyDealzRedirectsSanizierTest.kt
Labels: feature
